-- Add MFA and SSO fields to users table
ALTER TABLE users
ADD COLUMN IF NOT EXISTS mfaEnabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS mfaSecret TEXT,
ADD COLUMN IF NOT EXISTS mfaBackupCodes JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS ssoEnabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ssoProvider TEXT,
ADD COLUMN IF NOT EXISTS ssoProviderId TEXT,
ADD COLUMN IF NOT EXISTS ssoProviderData JSONB DEFAULT '{}';

-- Create identity providers table for SSO configurations
CREATE TABLE IF NOT EXISTS identity_providers (
  id SERIAL PRIMARY KEY,
  tenantId INTEGER NOT NULL,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  enabled BOOLEAN DEFAULT TRUE NOT NULL,
  config JSONB NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);